// The repository's editorial workflow, as the statuses a node's workflow history is written with
// (see RepositoryNodeService.addWorkflowStatus). The panel only ever writes one of them so far —
// the whole vocabulary is here because a status is meaningless without the ladder it sits on: the
// numbers are the order of the steps, and the 2xx entries undo their 1xx counterparts.

export enum WorkflowStatus {
  METADATA_RECORD_REQUESTED = '110_METADATA_RECORD_REQUESTED',
  METADATA_QUALITY_CONFIRMED = '120_METADATA_QUALITY_CONFIRMED',
  METADATA_QUALITY_FOR_BUFFET = '125_METADATA_QUALITY_FOR_BUFFET',
  ELEMENT_REJECTED = '130_ELEMENT_REJECTED',
  ELEMENT_LEGALLY_APPROVED = '140_ELEMENT_LEGALLY_APPROVED',
  ELEMENT_APPROVED_FOR_BUFFET = '145_ELEMENT_APPROVED_FOR_BUFFET',
  PUBLISH_IN_SEARCH = '150_PUBLISH_IN_SEARCH',
  ELEMENT_UNLOCK_BUFFET = '155_ELEMENT_UNLOCK_BUFFET',
  REMOVE_FROM_SEARCH = '160_REMOVE_FROM_SEARCH',
  CRAWLER_PUBLISH_IN_SEARCH = '170_CRAWLER_PUBLISH_IN_SEARCH',

  METADATA_RECORD_REQUESTED_REVERT = '210_METADATA_RECORD_REQUESTED_REVERT',
  METADATA_QUALITY_CONFIRMED_REVERT = '220_METADATA_QUALITY_CONFIRMED_REVERT',
  METADATA_QUALITY_FOR_BUFFET_REVERT = '225_METADATA_QUALITY_FOR_BUFFET_REVERT',
  ELEMENT_LEGALLY_APPROVED_REVERT = '240_ELEMENT_LEGALLY_APPROVED_REVERT',
  ELEMENT_APPROVED_FOR_BUFFET_REVERT = '245_ELEMENT_APPROVED_FOR_BUFFET_REVERT',
  ELEMENT_UNLOCK_BUFFET_REVERT = '255_ELEMENT_UNLOCK_BUFFET_REVERT',
  CRAWLER_PUBLISH_IN_SEARCH_REVERT = '270_CRAWLER_PUBLISH_IN_SEARCH_REVERT'
}
